// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nhid-clinical/Admin.tsx": () => import("../components/mockups/nhid-clinical/Admin.tsx"),
  "./components/mockups/nhid-clinical/Dashboard.tsx": () => import("../components/mockups/nhid-clinical/Dashboard.tsx"),
  "./components/mockups/nhid-clinical/Onboarding.tsx": () => import("../components/mockups/nhid-clinical/Onboarding.tsx")
};
