#!/usr/bin/env python3
"""
Record the real evaluator's output over the synthetic demo set.

Why this exists
---------------
The Governance Ops screens are entirely API-driven. Deployed without a reachable
backend they render empty, and a visitor cannot even obtain an API key, because
registration is itself an API call. So a published dashboard shows nothing.

The fix is *not* a second evaluator written in TypeScript. That is how a control
engine acquires a second opinion about its own controls and then drifts from it.
Instead this script drives the **real** stack -- the actual FastAPI app, the
actual `saas_layer/monitoring.py` evaluator, against a real database -- over the
committed demo interactions, and records the responses verbatim. The frontend
replays that recording when it has no backend.

What the frontend renders in demo mode is therefore output this engine actually
produced, not an imitation of it.

The pattern, and the `--check` mode, follow the framework's existing generators
(`build_gateway_fixture.py`, `build_walkthrough_fixture.py`,
`build_evidence_visuals.py`): committed output, regenerated by running the
engine, with CI failing the moment the two disagree.

Usage:
  python scripts/build_demo_fixture.py           # regenerate
  python scripts/build_demo_fixture.py --check   # fail if stale (CI)

Requires the same environment the test suite does: DATABASE_URL, HMAC_SECRET.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import uuid
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).resolve().parent.parent
REPO = ROOT.parent

SOURCE = REPO / "artifacts/nhid-saas/src/pages/ops/demo-interactions.json"
OUT = REPO / "artifacts/nhid-saas/src/pages/ops/demo-fixture.json"

# Anything derived from wall-clock time or a fresh uuid differs on every run and
# would make --check fail for no reason. Those fields are normalised to stable
# placeholders: the fixture records what the engine *decided*, not when it ran.
VOLATILE_EXACT = frozenset({
    "assessment_id", "interaction_id", "finding_id", "review_event_id",
    "org_id", "created_at", "evaluated_at", "generated_at", "resolved_at",
    "ingested_at", "updated_at",
})


def _stabilise(node: Any, ids: Dict[str, str]) -> Any:
    """Replace generated identifiers and timestamps with deterministic stand-ins.

    Identifiers are mapped consistently (the same uuid always becomes the same
    placeholder) so cross-references between an interaction, its findings and
    its evaluations still resolve in the recorded output.
    """
    if isinstance(node, dict):
        out = {}
        for key, value in node.items():
            if key in VOLATILE_EXACT and isinstance(value, str) and value:
                if key.endswith("_at"):
                    out[key] = "2026-09-08T00:00:00Z"
                else:
                    out[key] = ids.setdefault(
                        value, f"demo-{key[:-3]}-{len(ids) + 1:04d}"
                    )
            else:
                out[key] = _stabilise(value, ids)
        return out
    if isinstance(node, list):
        return [_stabilise(item, ids) for item in node]
    return node


def _finding_sort_key(finding: Dict[str, Any]) -> tuple:
    """Deterministic order for findings, independent of insertion order.

    `summary` is in the key not because the first three fields are expected to
    tie, but so that the order stays total if they ever do. A key that ties
    leaves two rows in whatever order the database returned, which is exactly
    the non-determinism this exists to remove.
    """
    return (
        finding.get("external_id") or "",
        finding.get("control_id") or "",
        finding.get("category") or "",
        finding.get("summary") or "",
    )


def build() -> Dict[str, Any]:
    """Drive the real app over the demo set and capture every response."""
    from fastapi.testclient import TestClient

    from saas_layer.auth import create_org, init_db
    from saas_layer.db import get_conn
    from saas_layer.gateway import app

    init_db()
    interactions = json.loads(SOURCE.read_text())

    org = create_org(f"demo-fixture-{uuid.uuid4().hex[:8]}")
    headers = {"X-API-Key": org["api_key"]}
    client = TestClient(app)

    try:
        created = client.post(
            "/saas/monitor/assessments",
            headers=headers,
            json={
                "name": "Q3 inbound provider-vendor calls",
                "period_start": "2026-09-01",
                "period_end": "2026-09-30",
                "is_synthetic": True,
            },
        )
        created.raise_for_status()
        assessment_id = created.json()["assessment_id"]

        ingested = client.post(
            "/saas/monitor/ingest",
            headers=headers,
            json={
                "assessment_id": assessment_id,
                "vendor": "generic",
                "interactions": interactions,
                "is_synthetic": True,
            },
        )
        ingested.raise_for_status()
        if ingested.json().get("errors"):
            raise SystemExit(f"ingestion reported errors: {ingested.json()['errors']}")

        evaluated = client.post(
            f"/saas/monitor/assessments/{assessment_id}/evaluate", headers=headers
        )
        evaluated.raise_for_status()

        def get(path: str) -> Any:
            response = client.get(path, headers=headers)
            response.raise_for_status()
            return response.json()

        rows = get(f"/saas/monitor/interactions?assessment_id={assessment_id}")
        findings = get(f"/saas/monitor/findings?assessment_id={assessment_id}")

        # Sort BEFORE anything reads these lists, not after.
        #
        # _stabilise numbers its placeholders by first encounter, so the number
        # a finding gets depends on the order it is walked in. These lists come
        # back in whatever order the database produced, which is not stable
        # across runs. Sorting afterwards puts the rows in the right order but
        # leaves the ids already assigned from the unsorted walk -- so two
        # findings on one interaction would swap ids between runs and --check
        # would fail with a diff that says nothing about the engine.
        #
        # Sorting here fixes the walk order itself, which fixes the ids, the
        # row order, and the order the per-row detail requests are made in.
        rows["interactions"].sort(key=lambda r: r["external_id"])
        findings["findings"].sort(key=_finding_sort_key)

        fixture = {
            "_comment": (
                "RECORDED, SYNTHETIC. Generated by "
                "nhid-clinical/scripts/build_demo_fixture.py by replaying "
                "artifacts/nhid-saas/src/pages/ops/demo-interactions.json through the "
                "real saas_layer/monitoring.py evaluator. Do not hand-edit: "
                "`build_demo_fixture.py --check` fails when this stops matching the "
                "engine. These are not observed calls and not customer data."
            ),
            "assessments": get("/saas/monitor/assessments")["assessments"],
            "interactions": rows["interactions"],
            "findings": findings["findings"],
            "metrics": get(f"/saas/monitor/metrics?assessment_id={assessment_id}"),
            "report": get(f"/saas/monitor/assessments/{assessment_id}/report"),
            # Keyed by external_id, which is authored in the demo set and so is
            # stable across runs -- unlike the generated interaction_id.
            "details": {
                row["external_id"]: get(
                    f"/saas/monitor/interactions/{row['interaction_id']}"
                )
                for row in rows["interactions"]
            },
            # A list, not a map. Keying this by finding_id would put a freshly
            # generated uuid in a *key* position, and key positions are not
            # rewritten by _stabilise -- which made every run differ from the
            # last and --check fail immediately after a regenerate. The frontend
            # builds its own lookup from the stabilised finding_id inside each
            # record.
            "finding_details": [
                get(f"/saas/monitor/findings/{f['finding_id']}")
                for f in findings["findings"]
            ],
        }
        # No sorting here: the lists were sorted above, before _stabilise walked
        # them, which is the only point at which sorting also fixes the ids.
        return _stabilise(fixture, {})
    finally:
        # The fixture is the deliverable; the rows were scaffolding. Leaving a
        # demo org behind in a real database would be a surprise later.
        conn = get_conn()
        try:
            with conn:
                conn.cursor().execute(
                    "DELETE FROM orgs WHERE org_id = %s", (org["org_id"],)
                )
        finally:
            conn.close()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed fixture no longer matches the engine",
    )
    args = parser.parse_args()

    sys.path.insert(0, str(ROOT))
    os.environ.setdefault("STRIPE_WEBHOOK_SECRET", "whsec_fixture_build_only")

    if not SOURCE.exists():
        print(f"FAIL: {SOURCE.relative_to(REPO)} is missing")
        return 1

    fresh = build()
    rendered = json.dumps(fresh, indent=2, sort_keys=True) + "\n"

    if args.check:
        if not OUT.exists():
            print(f"DEMO FIXTURE FAIL: {OUT.relative_to(REPO)} does not exist")
            return 1
        if OUT.read_text() != rendered:
            print(
                f"DEMO FIXTURE FAIL: {OUT.relative_to(REPO)} no longer matches the "
                "engine.\n"
                "  The recorded demo output and saas_layer/monitoring.py disagree, so "
                "the published\n"
                "  dashboard would show results this engine does not produce.\n"
                "  Regenerate: python scripts/build_demo_fixture.py"
            )
            return 1
        counts = (
            f"{len(fresh['interactions'])} interactions, "
            f"{len(fresh['findings'])} findings"
        )
        print(f"DEMO FIXTURE PASS: recorded output matches the engine ({counts})")
        return 0

    OUT.write_text(rendered)
    print(
        f"Wrote {OUT.relative_to(REPO)} "
        f"({len(fresh['interactions'])} interactions, "
        f"{len(fresh['findings'])} findings)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
